### PR TITLE
Add aarch64 support

### PR DESCRIPTION
**Pull request by nerohmot**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nerohmot** [comment]
@conda-forge-admin please rerender

**Comment by ccordoba12** [comment]
`wurlitzer` is missing in aarch64 before this can be merged.

**Comment by nerohmot** [comment]
I added wurlitzer ... this guy was't happy with azure, he wanted default ... I did change it, but he still didn't merge :-( will ping you when I see wurlitzer popping up.

**Comment by nerohmot** [comment]
ok, wurlitzer has now aarch64 support

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
Closing in favor of #48 because it has the default aarch64 provider.

**Pull request closed without merging**
