### PR TITLE
Update to 0.3.0

### PR DESCRIPTION
**Pull request by ccordoba12**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
Pinging @jjhelmus, @nehaljwani and @mingwandroid about this one. This is a new release of `spyder-kernels` for the stable Spyder branch.

This release has the following changes:

1. It adds [wurlitzer](https://github.com/conda-forge/wurlitzer-feedstock) as a new dependency, but only for Linux and macOS.
2. Due to this change, we stopped creating the package as `noarch`.

**Comment by jjhelmus** [comment]
Thanks for the ping @ccordoba12, `spyder-kernels` 0.3.0 packages are now available in `defaults`

**Comment by ccordoba12** [comment]
Thanks a lot @jjhelmus!

**Pull request merged**
