### PR TITLE
v0.4.1

### PR DESCRIPTION
**Pull request by ccordoba12**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
Please wait, there's a bug in this version that I'm fixing right now. I'll release 0.4.2 in an hour or so.

**Comment by jjhelmus** [comment]
@ccordoba12 Is a 0.4.2 release still expected soon or should I build and release 0.4.1 to defaults?

**Comment by ccordoba12** [comment]
No, no, please don't add 0.4.1 to defaults, it has a serious bug! I'll release 0.4.2 today.

**Pull request merged**
