### PR TITLE
Move 1.0+ versions to the beta channel

### PR DESCRIPTION
**Pull request by ccordoba12**

### CODE REVIEW

**Comment by ccordoba12** [comment]
@conda-forge/core or @isuruf, could you help me to move all `spyder-kernels` packages that have a version of 1.0 or higher to the `beta` channel? Those will be

    osx-64/spyder-kernels-1.2.0-py27_0.tar.bz2
    osx-64/spyder-kernels-1.2.0-py36_0.tar.bz2
    osx-64/spyder-kernels-1.2.0-py37_0.tar.bz2
    win-64/spyder-kernels-1.2.0-py27_0.tar.bz2
    win-64/spyder-kernels-1.2.0-py36_0.tar.bz2
    win-64/spyder-kernels-1.2.0-py37_0.tar.bz2
    linux-64/spyder-kernels-1.2.0-py27_0.tar.bz2
    linux-64/spyder-kernels-1.2.0-py37_0.tar.bz2
    linux-64/spyder-kernels-1.2.0-py36_0.tar.bz2
    noarch/spyder-kernels-1.1.0-py_0.tar.bz2
    noarch/spyder-kernels-1.0.3-py_0.tar.bz2
    noarch/spyder-kernels-1.0.1-py_2.tar.bz2
    noarch/spyder-kernels-1.0.1-py_1.tar.bz2
    osx-64/spyder-kernels-1.0.1-py36_0.tar.bz2
    osx-64/spyder-kernels-1.0.1-py35_0.tar.bz2
    osx-64/spyder-kernels-1.0.1-py27_0.tar.bz2
    win-64/spyder-kernels-1.0.1-py36_0.tar.bz2
    win-64/spyder-kernels-1.0.1-py35_0.tar.bz2
    win-64/spyder-kernels-1.0.1-py27_0.tar.bz2
    linux-64/spyder-kernels-1.0.1-py35_0.tar.bz2
    linux-64/spyder-kernels-1.0.1-py27_0.tar.bz2
    linux-64/spyder-kernels-1.0.1-py36_0.tar.bz2
    osx-64/spyder-kernels-1.0.0-py36_0.tar.bz2
    osx-64/spyder-kernels-1.0.0-py35_0.tar.bz2
    osx-64/spyder-kernels-1.0.0-py27_0.tar.bz2
    win-64/spyder-kernels-1.0.0-py36_0.tar.bz2
    win-64/spyder-kernels-1.0.0-py35_0.tar.bz2
    win-64/spyder-kernels-1.0.0-py27_0.tar.bz2
    linux-64/spyder-kernels-1.0.0-py27_0.tar.bz2
    linux-64/spyder-kernels-1.0.0-py35_0.tar.bz2
    linux-64/spyder-kernels-1.0.0-py36_0.tar.bz2

Even when Spyder has a requirement of [`spyder-kernels >=0.1,<1`](https://github.com/conda-forge/spyder-feedstock/blob/master/recipe/meta.yaml#L49), it seems people is incorrectly installing higher versions (which are only meant for Spyder 4, still in beta), perhaps by running `conda update --all`.

I thought the requirement was enough, but I can clearly see now that I was wrong. Thanks for your help!

**Comment by scopatz** [comment]
Moved to the beta label, but those pinnings should have worked....

**Comment by mariusvniekerk** [comment]
@ccordoba12 done.

**Comment by ccordoba12** [comment]
Thanks a lot @mariusvniekerk! And sorry for the hassle.

**Comment by ccordoba12** [comment]
@hmaarrfk, I think you'll be happy with this change.

**Comment by hmaarrfk** [comment]
mind blown!!!!!

**Pull request merged**
