### PR TITLE
Update to 0.5.0

### PR DESCRIPTION
**Pull request by ccordoba12**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
Pinging @jjhelmus about this one. This version is needed by the new Spyder release we're preparing right now (3.3.5).

**Comment by jjhelmus** [comment]
`spyder-kernels` 0.5.0 is now available in `defaults`

**Comment by ccordoba12** [comment]
Thanks a lot @jjhelmus!

**Pull request merged**
