### PR TITLE
skip problematic ipykernels 4.9.0

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ccordoba12** [comment]
> As is, it will skip 4.9.0 0 for all OSes

Please skip it only for Windows. It's working fine in other OSes.

**Comment by hmaarrfk** [comment]
Should I make it an arch dependent package then?

**Comment by ccordoba12** [comment]
> Should I make it an arch dependent package then?

Right, this is noarch package, sorry.

Ok, no problem then since this is a temporary workaround.

**Comment by hmaarrfk** [comment]
Yeah, that was my first line of processing too. I guess I should have kept the history. Thanks.

The != means that it should auto update to 4.9.1 when it comes out :D.

**Pull request merged**
