### PR TITLE
Update to 0.4.3

### PR DESCRIPTION
**Pull request by ccordoba12**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
Pinging @jjhelmus about this one. This version of spyder-kernels is required by the next version of Spyder (3.3.4).

**Comment by jjhelmus** [comment]
spyder-kernels 0.4.3 and spyder 3.3.4 are now available in `defaults`

**Comment by ccordoba12** [comment]
Thanks a lot @jjhelmus!

**Pull request merged**
